package zero_trust_access_application

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/cloudflare/terraform-provider-cloudflare/internal/services/zero_trust_access_application/migration/v500"
)

var _ resource.ResourceWithMoveState = (*ZeroTrustAccessApplicationResource)(nil)
var _ resource.ResourceWithUpgradeState = (*ZeroTrustAccessApplicationResource)(nil)

// MoveState handles moves from cloudflare_access_application (v4) to cloudflare_zero_trust_access_application (v5).
// This is triggered when users use the `moved` block (Terraform 1.8+), which tf-migrate generates
// automatically when renaming cloudflare_access_application resources.
func (r *ZeroTrustAccessApplicationResource) MoveState(ctx context.Context) []resource.StateMover {
	return []resource.StateMover{
		{
			// SourceSchema is intentionally not set. We parse req.SourceRawState
			// manually in MoveFromAccessApplication using the v4 schema type, so
			// that parsing errors surface as explicit diagnostics rather than
			// causing the framework to silently skip the mover.
			StateMover: v500.MoveFromAccessApplication,
		},
	}
}

// UpgradeState handles schema version upgrades for existing cloudflare_zero_trust_access_application state.
//
// State version map:
//
//	0 → v5.12–v5.16: schema Version was not set, defaulted to 0. State is v5 format.
//	1 → v5.17–v5.18: Version: 1. State is v5 format.
//
// Both are no-op pass-throughs: the attributes are already in v5 format and compatible
// with the current schema (new attributes added since v5.12 will simply be null).
//
// v4 → v5 migration is handled by MoveState (via `moved` blocks generated by tf-migrate),
// not here. UpgradeState only sees cloudflare_zero_trust_access_application state.
func (r *ZeroTrustAccessApplicationResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	v5Schema := ResourceSchema(ctx)
	return map[int64]resource.StateUpgrader{
		0: {
			PriorSchema:   &v5Schema,
			StateUpgrader: v500.UpgradeFromV0,
		},
		1: {
			PriorSchema:   &v5Schema,
			StateUpgrader: v500.UpgradeFromV1,
		},
	}
}
