name: grit-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: grit-check
        uses: getgrit/github-action-check@v0
