version: "1.0"
description: "Cloudflare Terraform Provider v5 Resource Renames for State Files"

# Important note about resource renames in state
notes:
  - "Resource renames in state files require careful handling"
  - "See https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/migrating-renamed-resources"
  - "You likely don't want to run this unless you know what you're doing"
  - "Dependencies must also be updated to maintain state consistency"
  - "Always backup your state file before performing renames"

# Resource type renames for state files (.tfstate)
state_resource_renames:
  # Zero Trust Access Resources
  cloudflare_access_application: cloudflare_zero_trust_access_application
  cloudflare_access_ca_certificate: cloudflare_zero_trust_access_short_lived_certificate
  cloudflare_access_custom_page: cloudflare_zero_trust_access_custom_page
  cloudflare_access_group: cloudflare_zero_trust_access_group
  cloudflare_access_identity_provider: cloudflare_zero_trust_access_identity_provider
  cloudflare_access_keys_configuration: cloudflare_zero_trust_access_key_configuration
  cloudflare_access_mutual_tls_certificate: cloudflare_zero_trust_access_mtls_certificate
  cloudflare_access_mutual_tls_hostname_settings: cloudflare_zero_trust_access_mtls_hostname_settings
  cloudflare_access_organization: cloudflare_zero_trust_organization
  cloudflare_access_policy: cloudflare_zero_trust_access_policy
  cloudflare_access_service_token: cloudflare_zero_trust_access_service_token
  cloudflare_access_tag: cloudflare_zero_trust_access_tag
  
  # Zero Trust Device Resources
  cloudflare_device_dex_test: cloudflare_zero_trust_dex_test
  cloudflare_device_managed_networks: cloudflare_zero_trust_device_managed_networks
  cloudflare_device_policy_certificates: cloudflare_zero_trust_device_certificates
  cloudflare_device_posture_integration: cloudflare_zero_trust_device_posture_integration
  cloudflare_device_posture_rule: cloudflare_zero_trust_device_posture_rule
  cloudflare_device_settings_policy: cloudflare_zero_trust_device_profiles
  
  # Zero Trust DLP Resources
  cloudflare_dlp_profile: cloudflare_zero_trust_dlp_profile
  cloudflare_dlp_custom_profile: cloudflare_zero_trust_dlp_custom_profile
  cloudflare_dlp_predefined_profile: cloudflare_zero_trust_dlp_predefined_profile
  
  # Zero Trust Gateway Resources
  cloudflare_gateway_app_types: cloudflare_zero_trust_gateway_app_types
  cloudflare_teams_account: cloudflare_zero_trust_gateway_settings
  cloudflare_teams_list: cloudflare_zero_trust_list
  cloudflare_teams_location: cloudflare_zero_trust_dns_location
  cloudflare_teams_proxy_endpoint: cloudflare_zero_trust_gateway_proxy_endpoint
  cloudflare_teams_rule: cloudflare_zero_trust_gateway_policy
  
  # Magic WAN Resources
  cloudflare_gre_tunnel: cloudflare_magic_wan_gre_tunnel
  cloudflare_ipsec_tunnel: cloudflare_magic_wan_ipsec_tunnel
  cloudflare_static_route: cloudflare_magic_wan_static_route
  
  # Zero Trust Tunnel Resources
  cloudflare_tunnel: cloudflare_zero_trust_tunnel_cloudflared
  cloudflare_tunnel_config: cloudflare_zero_trust_tunnel_cloudflared_config
  cloudflare_tunnel_route: cloudflare_zero_trust_tunnel_cloudflared_route
  cloudflare_tunnel_virtual_network: cloudflare_zero_trust_tunnel_cloudflared_virtual_network
  
  # Other Resources
  cloudflare_risk_behavior: cloudflare_zero_trust_risk_behavior
  cloudflare_split_tunnel: cloudflare_zero_trust_split_tunnels
  cloudflare_workers_for_platforms_namespace: cloudflare_workers_for_platforms_dispatch_namespace
  cloudflare_managed_headers: cloudflare_managed_transforms

# Dependency rename patterns
# When resources are renamed, their references in dependencies must also be updated
dependency_rename_patterns:
  description: "Patterns for updating resource dependencies in state"
  patterns:
    # Pattern: cloudflare_access_application.$dep -> cloudflare_zero_trust_access_application.$dep
    # This ensures that when other resources depend on renamed resources, those dependencies are updated
    - from_prefix: "cloudflare_access_application."
      to_prefix: "cloudflare_zero_trust_access_application."
    - from_prefix: "cloudflare_access_ca_certificate."
      to_prefix: "cloudflare_zero_trust_access_short_lived_certificate."
    - from_prefix: "cloudflare_access_custom_page."
      to_prefix: "cloudflare_zero_trust_access_custom_page."
    - from_prefix: "cloudflare_access_group."
      to_prefix: "cloudflare_zero_trust_access_group."
    - from_prefix: "cloudflare_access_identity_provider."
      to_prefix: "cloudflare_zero_trust_access_identity_provider."
    - from_prefix: "cloudflare_access_keys_configuration."
      to_prefix: "cloudflare_zero_trust_access_key_configuration."
    - from_prefix: "cloudflare_access_mutual_tls_certificate."
      to_prefix: "cloudflare_zero_trust_access_mtls_certificate."
    - from_prefix: "cloudflare_access_mutual_tls_hostname_settings."
      to_prefix: "cloudflare_zero_trust_access_mtls_hostname_settings."
    - from_prefix: "cloudflare_access_organization."
      to_prefix: "cloudflare_zero_trust_organization."
    - from_prefix: "cloudflare_access_policy."
      to_prefix: "cloudflare_zero_trust_access_policy."
    - from_prefix: "cloudflare_access_service_token."
      to_prefix: "cloudflare_zero_trust_access_service_token."
    - from_prefix: "cloudflare_access_tag."
      to_prefix: "cloudflare_zero_trust_access_tag."
    - from_prefix: "cloudflare_device_dex_test."
      to_prefix: "cloudflare_zero_trust_dex_test."
    - from_prefix: "cloudflare_device_managed_networks."
      to_prefix: "cloudflare_zero_trust_device_managed_networks."
    - from_prefix: "cloudflare_device_policy_certificates."
      to_prefix: "cloudflare_zero_trust_device_certificates."
    - from_prefix: "cloudflare_device_posture_integration."
      to_prefix: "cloudflare_zero_trust_device_posture_integration."
    - from_prefix: "cloudflare_device_posture_rule."
      to_prefix: "cloudflare_zero_trust_device_posture_rule."
    - from_prefix: "cloudflare_device_settings_policy."
      to_prefix: "cloudflare_zero_trust_device_profiles."
    - from_prefix: "cloudflare_dlp_custom_profile."
      to_prefix: "cloudflare_zero_trust_dlp_custom_profile."
    - from_prefix: "cloudflare_dlp_predefined_profile."
      to_prefix: "cloudflare_zero_trust_dlp_predefined_profile."
    - from_prefix: "cloudflare_dlp_profile."
      to_prefix: "cloudflare_zero_trust_dlp_profile."
    - from_prefix: "cloudflare_gateway_app_types."
      to_prefix: "cloudflare_zero_trust_gateway_app_types."
    - from_prefix: "cloudflare_gre_tunnel."
      to_prefix: "cloudflare_magic_wan_gre_tunnel."
    - from_prefix: "cloudflare_ipsec_tunnel."
      to_prefix: "cloudflare_magic_wan_ipsec_tunnel."
    - from_prefix: "cloudflare_risk_behavior."
      to_prefix: "cloudflare_zero_trust_risk_behavior."
    - from_prefix: "cloudflare_split_tunnel."
      to_prefix: "cloudflare_zero_trust_split_tunnels."
    - from_prefix: "cloudflare_static_route."
      to_prefix: "cloudflare_magic_wan_static_route."
    - from_prefix: "cloudflare_teams_account."
      to_prefix: "cloudflare_zero_trust_gateway_settings."
    - from_prefix: "cloudflare_teams_list."
      to_prefix: "cloudflare_zero_trust_list."
    - from_prefix: "cloudflare_teams_location."
      to_prefix: "cloudflare_zero_trust_dns_location."
    - from_prefix: "cloudflare_teams_proxy_endpoint."
      to_prefix: "cloudflare_zero_trust_gateway_proxy_endpoint."
    - from_prefix: "cloudflare_teams_rule."
      to_prefix: "cloudflare_zero_trust_gateway_policy."
    - from_prefix: "cloudflare_tunnel."
      to_prefix: "cloudflare_zero_trust_tunnel_cloudflared."
    - from_prefix: "cloudflare_tunnel_config."
      to_prefix: "cloudflare_zero_trust_tunnel_cloudflared_config."
    - from_prefix: "cloudflare_tunnel_route."
      to_prefix: "cloudflare_zero_trust_tunnel_cloudflared_route."
    - from_prefix: "cloudflare_tunnel_virtual_network."
      to_prefix: "cloudflare_zero_trust_tunnel_cloudflared_virtual_network."
    - from_prefix: "cloudflare_workers_for_platforms_namespace."
      to_prefix: "cloudflare_workers_for_platforms_dispatch_namespace."
    - from_prefix: "cloudflare_managed_headers."
      to_prefix: "cloudflare_managed_transforms."

# State file structure notes
state_structure:
  description: "How resource renames affect state file structure"
  affected_fields:
    - "resources[].type - The resource type name"
    - "resources[].instances[].dependencies - References to other resources"
    - "resources[].provider - Provider reference (unchanged)"
    - "outputs may reference renamed resources (manual update required)"

# Safety checks
safety_checks:
  - "Verify state file backup exists before proceeding"
  - "Check that no resources will be destroyed and recreated"
  - "Ensure all dependencies are updated correctly"
  - "Run terraform plan after state modifications to verify"
  - "Test in a non-production environment first"