version: "1.0"
description: "Cloudflare Terraform Provider v5 Resource Renames for Configuration Files"

# Important note about resource renames
notes:
  - "Resource renames require special handling in Terraform"
  - "See https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/migrating-renamed-resources"
  - "You likely don't want to run this unless you know what you're doing"
  - "State must be migrated separately using terraform state mv commands"

# Resource type renames for configuration files (.tf)
resource_renames:
  # Zero Trust Access Resources
  cloudflare_access_application: cloudflare_zero_trust_access_application
  cloudflare_access_ca_certificate: cloudflare_zero_trust_access_short_lived_certificate
  cloudflare_access_custom_page: cloudflare_zero_trust_access_custom_page
  cloudflare_access_group: cloudflare_zero_trust_access_group
  cloudflare_access_identity_provider: cloudflare_zero_trust_access_identity_provider
  cloudflare_access_keys_configuration: cloudflare_zero_trust_access_key_configuration
  cloudflare_access_mutual_tls_certificate: cloudflare_zero_trust_access_mtls_certificate
  cloudflare_access_mutual_tls_hostname_settings: cloudflare_zero_trust_access_mtls_hostname_settings
  cloudflare_access_organization: cloudflare_zero_trust_organization
  cloudflare_access_policy: cloudflare_zero_trust_access_policy
  cloudflare_access_service_token: cloudflare_zero_trust_access_service_token
  cloudflare_access_tag: cloudflare_zero_trust_access_tag
  
  # Zero Trust Device Resources
  cloudflare_device_dex_test: cloudflare_zero_trust_dex_test
  cloudflare_device_managed_networks: cloudflare_zero_trust_device_managed_networks
  cloudflare_device_policy_certificates: cloudflare_zero_trust_device_certificates
  cloudflare_device_posture_integration: cloudflare_zero_trust_device_posture_integration
  cloudflare_device_posture_rule: cloudflare_zero_trust_device_posture_rule
  cloudflare_device_settings_policy: cloudflare_zero_trust_device_profiles
  
  # Zero Trust DLP Resources
  cloudflare_dlp_custom_profile: cloudflare_zero_trust_dlp_custom_profile
  cloudflare_dlp_predefined_profile: cloudflare_zero_trust_dlp_predefined_profile
  cloudflare_dlp_profile: cloudflare_zero_trust_dlp_profile
  
  # Zero Trust Gateway Resources
  cloudflare_gateway_app_types: cloudflare_zero_trust_gateway_app_types
  cloudflare_teams_account: cloudflare_zero_trust_gateway_settings
  cloudflare_teams_list: cloudflare_zero_trust_list
  cloudflare_teams_location: cloudflare_zero_trust_dns_location
  cloudflare_teams_proxy_endpoint: cloudflare_zero_trust_gateway_proxy_endpoint
  cloudflare_teams_rule: cloudflare_zero_trust_gateway_policy
  
  # Magic WAN Resources
  cloudflare_gre_tunnel: cloudflare_magic_wan_gre_tunnel
  cloudflare_ipsec_tunnel: cloudflare_magic_wan_ipsec_tunnel
  cloudflare_static_route: cloudflare_magic_wan_static_route
  
  # Zero Trust Tunnel Resources
  cloudflare_tunnel: cloudflare_zero_trust_tunnel_cloudflared
  cloudflare_tunnel_config: cloudflare_zero_trust_tunnel_cloudflared_config
  cloudflare_tunnel_route: cloudflare_zero_trust_tunnel_cloudflared_route
  cloudflare_tunnel_virtual_network: cloudflare_zero_trust_tunnel_cloudflared_virtual_network
  
  # Other Resources
  cloudflare_risk_behavior: cloudflare_zero_trust_risk_behavior
  cloudflare_split_tunnel: cloudflare_zero_trust_split_tunnels
  cloudflare_workers_for_platforms_namespace: cloudflare_workers_for_platforms_dispatch_namespace
  cloudflare_managed_headers: cloudflare_managed_transforms

# Resource categories for documentation
resource_categories:
  zero_trust_access:
    - cloudflare_access_application
    - cloudflare_access_ca_certificate
    - cloudflare_access_custom_page
    - cloudflare_access_group
    - cloudflare_access_identity_provider
    - cloudflare_access_keys_configuration
    - cloudflare_access_mutual_tls_certificate
    - cloudflare_access_mutual_tls_hostname_settings
    - cloudflare_access_organization
    - cloudflare_access_policy
    - cloudflare_access_service_token
    - cloudflare_access_tag
  
  zero_trust_device:
    - cloudflare_device_dex_test
    - cloudflare_device_managed_networks
    - cloudflare_device_policy_certificates
    - cloudflare_device_posture_integration
    - cloudflare_device_posture_rule
    - cloudflare_device_settings_policy
  
  zero_trust_dlp:
    - cloudflare_dlp_custom_profile
    - cloudflare_dlp_predefined_profile
    - cloudflare_dlp_profile
  
  zero_trust_gateway:
    - cloudflare_gateway_app_types
    - cloudflare_teams_account
    - cloudflare_teams_list
    - cloudflare_teams_location
    - cloudflare_teams_proxy_endpoint
    - cloudflare_teams_rule
  
  magic_wan:
    - cloudflare_gre_tunnel
    - cloudflare_ipsec_tunnel
    - cloudflare_static_route
  
  zero_trust_tunnel:
    - cloudflare_tunnel
    - cloudflare_tunnel_config
    - cloudflare_tunnel_route
    - cloudflare_tunnel_virtual_network
  
  other:
    - cloudflare_risk_behavior
    - cloudflare_split_tunnel
    - cloudflare_workers_for_platforms_namespace
    - cloudflare_managed_headers

# Migration guidance
migration_guidance:
  description: "Steps to handle resource renames properly"
  steps:
    - "Update configuration files (.tf) to use new resource names"
    - "Run terraform state mv commands to rename resources in state"
    - "Example: terraform state mv cloudflare_access_application.example cloudflare_zero_trust_access_application.example"
    - "Verify no resources will be destroyed and recreated"
    - "Run terraform plan to confirm no changes"