package ai_search_namespace_test

import (
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/cloudflare/cloudflare-go/v6"
	"github.com/cloudflare/cloudflare-go/v6/ai_search"
	"github.com/cloudflare/cloudflare-go/v6/option"
	"github.com/cloudflare/terraform-provider-cloudflare/internal/acctest"
	"github.com/cloudflare/terraform-provider-cloudflare/internal/consts"
	"github.com/cloudflare/terraform-provider-cloudflare/internal/utils"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

// testClient returns a Cloudflare API client supporting either API key+email or
// API token credentials. Falls back to acctest.SharedClient() when only key+email
// are set, but constructs a token-based client when CLOUDFLARE_API_TOKEN is set.
func testClient() *cloudflare.Client {
	if token := os.Getenv("CLOUDFLARE_API_TOKEN"); token != "" {
		return cloudflare.NewClient(option.WithAPIToken(token))
	}
	return acctest.SharedClient()
}

func TestMain(m *testing.M) {
	resource.TestMain(m)
}

func init() {
	resource.AddTestSweepers("cloudflare_ai_search_namespace", &resource.Sweeper{
		Name: "cloudflare_ai_search_namespace",
		F:    testSweepCloudflareAISearchNamespaces,
	})
}

func testSweepCloudflareAISearchNamespaces(region string) error {
	client := testClient()
	accountID := os.Getenv("CLOUDFLARE_ACCOUNT_ID")

	ctx := context.Background()
	page, err := client.AISearch.Namespaces.List(ctx, ai_search.NamespaceListParams{
		AccountID: cloudflare.F(accountID),
	})
	if err != nil {
		return fmt.Errorf("failed to fetch AI Search namespaces: %w", err)
	}

	for page != nil && len(page.Result) > 0 {
		for _, namespace := range page.Result {
			// Only sweep resources created by acceptance tests.
			if !isTestResource(namespace.Name) {
				continue
			}
			_, err := client.AISearch.Namespaces.Delete(
				ctx,
				namespace.Name,
				ai_search.NamespaceDeleteParams{
					AccountID: cloudflare.F(accountID),
				},
			)
			if err != nil {
				return fmt.Errorf("failed to delete AI Search namespace %q: %w", namespace.Name, err)
			}
		}

		page, err = page.GetNextPage()
		if err != nil {
			break
		}
	}

	return nil
}

// isTestResource returns true for names generated by GenerateRandomResourceName
// (10 lowercase alpha chars). The sweeper conservatively skips anything that
// doesn't match to avoid clobbering real resources during prod-targeted runs.
func isTestResource(name string) bool {
	if len(name) != utils.ResourceNameLength {
		return false
	}
	for _, r := range name {
		if r < 'a' || r > 'z' {
			return false
		}
	}
	return true
}

func TestAccCloudflareAISearchNamespace_Basic(t *testing.T) {
	rnd := utils.GenerateRandomResourceName()
	accountID := os.Getenv("CLOUDFLARE_ACCOUNT_ID")
	resourceName := "cloudflare_ai_search_namespace." + rnd

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.TestAccPreCheck(t)
			acctest.TestAccPreCheck_AccountID(t)
		},
		ProtoV6ProviderFactories: acctest.TestAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCloudflareAISearchNamespaceDestroy,
		Steps: []resource.TestStep{
			// Create + Read + verify empty plan/refresh.
			{
				Config: testAccCheckCloudflareAISearchNamespaceBasic(rnd, accountID),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rnd)),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("account_id"), knownvalue.StringExact(accountID)),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact("tf-acctest namespace")),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("created_at"), knownvalue.NotNull()),
				},
			},
			// Update description and verify only that field changes.
			{
				Config: testAccCheckCloudflareAISearchNamespaceBasicUpdated(rnd, accountID),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("name"), knownvalue.StringExact(rnd)),
					statecheck.ExpectKnownValue(resourceName, tfjsonpath.New("description"), knownvalue.StringExact("tf-acctest namespace updated")),
				},
			},
			// Import test skipped: ImportState is not implemented for this resource
			// (the underlying API uses {name} as the path identifier rather than {id},
			// which Stainless does not auto-wire for import).
		},
	})
}

func testAccCheckCloudflareAISearchNamespaceBasic(rnd, accountID string) string {
	return acctest.LoadTestCase("aisearchnamespacebasic.tf", rnd, accountID)
}

func testAccCheckCloudflareAISearchNamespaceBasicUpdated(rnd, accountID string) string {
	return acctest.LoadTestCase("aisearchnamespacebasicupdated.tf", rnd, accountID)
}

func testAccCheckCloudflareAISearchNamespaceDestroy(s *terraform.State) error {
	client := testClient()

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "cloudflare_ai_search_namespace" {
			continue
		}

		accountID := rs.Primary.Attributes[consts.AccountIDSchemaKey]
		_, err := client.AISearch.Namespaces.Read(
			context.Background(),
			rs.Primary.Attributes["name"],
			ai_search.NamespaceReadParams{
				AccountID: cloudflare.F(accountID),
			},
		)
		if err == nil {
			return fmt.Errorf("AI Search namespace still exists")
		}
	}

	return nil
}
