package v500

import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// MoveStateFromTunnelConfig handles state moves from cloudflare_tunnel_config (deprecated v4 resource)
// to cloudflare_zero_trust_tunnel_cloudflared_config (v5 resource).
//
// This is triggered when users use the `moved` block (Terraform 1.8+) generated by tf-migrate:
//
//	moved {
//	    from = cloudflare_tunnel_config.example
//	    to   = cloudflare_zero_trust_tunnel_cloudflared_config.example
//	}
//
// The source state is in v4 SDKv2 format (schema_version=0) and must be fully transformed.
func MoveStateFromTunnelConfig(
	ctx context.Context,
	req resource.MoveStateRequest,
	resp *resource.MoveStateResponse,
) {
	// Verify source is cloudflare_tunnel_config from cloudflare provider
	if req.SourceTypeName != "cloudflare_tunnel_config" {
		return
	}

	if !isCloudflareProvider(req.SourceProviderAddress) {
		return
	}

	tflog.Info(ctx, "Starting state move from cloudflare_tunnel_config to cloudflare_zero_trust_tunnel_cloudflared_config",
		map[string]interface{}{
			"source_type":           req.SourceTypeName,
			"source_schema_version": req.SourceSchemaVersion,
			"source_provider":       req.SourceProviderAddress,
		})

	// Parse the source state using v4 model
	var sourceState SourceV4TunnelConfigModel
	resp.Diagnostics.Append(req.SourceState.Get(ctx, &sourceState)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Transform source state to target state
	targetState, diags := Transform(ctx, sourceState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set the target state
	resp.Diagnostics.Append(resp.TargetState.Set(ctx, targetState)...)

	tflog.Info(ctx, "State move from cloudflare_tunnel_config to cloudflare_zero_trust_tunnel_cloudflared_config completed successfully")
}

func isCloudflareProvider(addr string) bool {
	return strings.Contains(addr, "cloudflare/cloudflare") ||
		strings.Contains(addr, "registry.terraform.io/cloudflare")
}
