// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package teams_location

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

var _ datasource.DataSourceWithConfigValidators = &TeamsLocationDataSource{}
var _ datasource.DataSourceWithValidateConfig = &TeamsLocationDataSource{}

func (r TeamsLocationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_id": schema.StringAttribute{
				Optional: true,
			},
			"location_id": schema.StringAttribute{
				Optional: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
			"client_default": schema.BoolAttribute{
				Description: "True if the location is the default location.",
				Computed:    true,
				Optional:    true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
			"doh_subdomain": schema.StringAttribute{
				Description: "The DNS over HTTPS domain to send DNS requests to. This field is auto-generated by Gateway.",
				Computed:    true,
				Optional:    true,
			},
			"ecs_support": schema.BoolAttribute{
				Description: "True if the location needs to resolve EDNS queries.",
				Computed:    true,
				Optional:    true,
			},
			"ip": schema.StringAttribute{
				Description: "IPV6 destination ip assigned to this location. DNS requests sent to this IP will counted as the request under this location. This field is auto-generated by Gateway.",
				Computed:    true,
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Description: "The name of the location.",
				Computed:    true,
				Optional:    true,
			},
			"networks": schema.ListNestedAttribute{
				Description: "A list of network ranges that requests from this location would originate from.",
				Computed:    true,
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"network": schema.StringAttribute{
							Description: "The IPv4 address or IPv4 CIDR. IPv4 CIDRs are limited to a maximum of /24.",
							Computed:    true,
						},
					},
				},
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
			"find_one_by": schema.SingleNestedAttribute{
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"account_id": schema.StringAttribute{
						Required: true,
					},
				},
			},
		},
	}
}

func (r *TeamsLocationDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{}
}

func (r *TeamsLocationDataSource) ValidateConfig(ctx context.Context, req datasource.ValidateConfigRequest, resp *datasource.ValidateConfigResponse) {
}
