#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/cloudflare-go/v7"

go build -o terraform-provider-cloudflare
