#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cloudflare/cloudflare-go/v6,github.com/stainless-sdks/cloudflare-go/v6"

cd "$(dirname "$0")/.."

if [ -z "$1" ]; then
  echo "Error: You must define a version number to inject into the build"
  exit 1
fi

VERSION=$1
echo "==> Building provider version $VERSION"
go build -ldflags="-s -w -X main.version=$VERSION" -o terraform-provider-cloudflare
