#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cloudflare/cloudflare-go,github.com/gitlab.cfdata.org/cloudflare/sdks/cloudflare-go"

echo "==> Running Go build"
go build ./...

echo ""
echo "==> Running sweeper linter"
./scripts/lint-sweepers
