#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/cloudflare/cloudflare-go/v6,github.com/stainless-sdks/cloudflare-go/v6"

echo "==> Running Go build"
go build ./...

echo ""
echo "==> Running sweeper linter"
./scripts/lint-sweepers
