name: CI
on:
  push:
    branches:
      - '**'
      - '!integrated/**'
      - '!stl-preview-head/**'
      - '!stl-preview-base/**'
      - '!generated'
      - '!codegen/**'
      - 'codegen/stl/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

env:
  GOPRIVATE: github.com/cloudflare/cloudflare-go/v6,github.com/stainless-sdks/cloudflare-go/v6

jobs:
  lint:
    runs-on: ${{ github.repository == 'stainless-sdks/cloudflare-terraform' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/cloudflare-terraform'
        run: |
          ./scripts/link 'github.com/stainless-sdks/cloudflare-go/v6@${{ github.ref_name }}' || go mod edit -dropreplace='github.com/stainless-sdks/cloudflare-go/v6'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run lints
        run: ./scripts/lint

  test:
    runs-on: ${{ github.repository == 'stainless-sdks/cloudflare-terraform' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/cloudflare-terraform'
        run: |
          ./scripts/link 'github.com/stainless-sdks/cloudflare-go/v6@${{ github.ref_name }}' || go mod edit -dropreplace='github.com/stainless-sdks/cloudflare-go/v6'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test