---
name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  terraform-provider-release:
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v4
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-private-key-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    with:
      setup-go-version-file: 'go.mod'
      goreleaser-release-args: '--clean'
