name: Sync branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-release-branch:
    name: Sync to release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: '4.x'
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false
